### เปรียบเทียบประสิทธิภาพ LLM ในการตรวจจับ Scam (Qwen, OpenAI, Gemini)

In [4]:
import os
import pandas as pd
from openrouter import OpenRouter
from dotenv import load_dotenv  

load_dotenv()
api_key=os.getenv("OPENROUTER_API_KEY")

In [1]:
SYSTEM_PROMPT = """
Role: คุณเป็นผู้เชี่ยวชาญด้านการวิเคราะห์ SMS หลอกลวง ในประเทศไทย และเป็นหน่วยรักษาความปลอดภัยทางไซเบอร์มานานกว่า 50 ปี

Task: ช้อความต่อไปนี้เป็นข้อความที่ส่งมาจาก sms ซึ่งใน ข้อความเหล่านี้จะมีทั้งข้อความปกติ และ ข้อความจากแสกมเมอร์ 
หน้าที่ของคุณคือวิเคราะห์ว่า sms เป็นข้อความปกติ หรือ ข้อความจากแสกมเมอร์พร้อมให้เหตุผล แล้วสรุปผลออกมาสั้นๆ
"""

def qwen_analysis (text):
    with OpenRouter(api_key=api_key) as client:
        response = client.chat.send(
            model="qwen/qwen3-32b",
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ]
        )

    return response.choices[0].message.content
def glm_analysis (text):
    with OpenRouter(api_key=api_key) as client:
        response = client.chat.send(
            model="z-ai/glm-4.5-air",
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ]
        )

    return response.choices[0].message.content

In [5]:
test_messages = [
    #Scam messages
    "ธนาคารได้อนุมัติวงเงิน50,000บาทติดต่อรับสิทธิ์: https://rb.gy/2erksz",
    "คุณได้รับคืนเงินประกันมิเตอร์ไฟฟ้าส่วนภูมิภาค PEA ซึ่งจะคืนตามขนาดของมิเตอร์ที่ใช้ สามารถสอบถามเพิ่มเติมได้ที่ https://bit.ly/44jHSpi",
    "KMA ยื่นสิทธิ์การกู้ให้ท่าน 120,000 บาท คลิก: citly.me/eq9br ",
    "เงินเข้าโทรศัพท์ฟรี 500บาท กด*158# ลุ้นก่อนใคร สมัครดวงดีดวงเฮง 3บ/ขค",
    "รับฟรี 129 บาท ฝากแรกรับ 1599 บาท",
    #Normal messages
    "AIS ยกขบวนมือถือรุ่นเด็ด พร้อมโปรโมชันส่วนลดจัดเต็มในงาน Thailand Mobile Expo ณ ศูนย์การประชุมแห่งชาติสิริกิติ์ ระหว่างวันที่ 8-11 กุมภาพันธ์ 2567 เตรียมมาชอปมือถือใหม่ รับปีมังกร พร้อมลดภาษีได้เต็ม Max (ขึ้นอยู่กับอัตราเงินได้สุทธิที่เสียภาษี) แล้วพบกันภายในงานตั้งแต่ 10.00 น. – 20.00 น.",
    "OTP 930917 (ref. 8697) สำหรับสมัคร myID อย่าบอกรหัสนี้กับบุคคลอื่น",
    "ใจฟู เน็ตฟูลสปีด! เล่นไม่สะดุด 50วัน 199บ. 30วัน ถึง 29 ก.พ.67 คลิก https://dtac.co.th/s/CMTDTE5",
    "[ ⬛️ Express] พัสดุ ⬛️⬛️ จัดส่งสำเร็จแล้ว ตรวจสอบได้ที่เว็บไซต์ ⬛️ Express Thailandหากมีข้อสงสัย กรุณาติดต่อ call center 1470",
    "มีผู้เข้าสู่ระบบธนาคารของคุณจากอุปกรณ์อื่น หากไม่ได้ดำเนินการด้วยตนเอง โปรดติดต่อทันที kasikorn.go-line.cc"
    ]

results = []
for msg in test_messages:
    results.append({
        "Message": msg,
        "qwen3-32b ": qwen_analysis(msg),
        "glm-4.5-air": glm_analysis(msg)
    })

df_results = pd.DataFrame(results)
display(df_results)

,Message,qwen3-32b,glm-4.5-air
0,"ธนาคารได้อนุมัติวงเงิน50,000บาทติดต่อรับสิทธิ์...",**วิเคราะห์ SMS:** \nข้อความนี้มีลักษณะคล้ายข...,### ผลการวิเคราะห์ SMS:\n**เป็นข้อความจากแสกมเ...
1,คุณได้รับคืนเงินประกันมิเตอร์ไฟฟ้าส่วนภูมิภาค ...,"**วิเคราะห์ SMS ข้อความที่ได้รับ** \nคำว่า ""ค...",**การวิเคราะห์ SMS**\n\nหมายเหตุ: ข้อความนี้เป...
2,"KMA ยื่นสิทธิ์การกู้ให้ท่าน 120,000 บาท คลิก: ...",ข้อความนี้เป็น **ข้อความหลอกลวง (Scam SMS)** เ...,"### วิเคราะห์ข้อความ SMS:\n**ข้อความ:** ""KMA ย..."
3,เงินเข้าโทรศัพท์ฟรี 500บาท กด*158# ลุ้นก่อนใคร...,**วิเคราะห์ว่าเป็นข้อความปกติหรือแสกมเมอร์:** ...,**การวิเคราะห์ข้อความนี้:**\n\nข้อความนี้เป็น ...
4,รับฟรี 129 บาท ฝากแรกรับ 1599 บาท,"**วิเคราะห์ SMS:** \nข้อความ ""รับฟรี 129 บาท ...",**ผลการวิเคราะห์: ข้อความหลอกลวง (Scam)**\n\n*...
5,AIS ยกขบวนมือถือรุ่นเด็ด พร้อมโปรโมชันส่วนลดจั...,**บทสรุป:** \nข้อความข้างต้นเป็น **ข้อความปกต...,### การวิเคราะห์ข้อความ SMS\n\n**ประเภทข้อความ...
6,OTP 930917 (ref. 8697) สำหรับสมัคร myID อย่าบอ...,**วิเคราะห์ SMS:** \nข้อความนี้เป็นข้อความปกต...,**การวิเคราะห์ (Analysis):**\n\nข้อความนี้มีคว...
7,ใจฟู เน็ตฟูลสปีด! เล่นไม่สะดุด 50วัน 199บ. 30ว...,**วิเคราะห์**: ข้อความนี้มีลักษณะคล้ายข่าวร้าย...,**ผลการวิเคราะห์: ข้อความปกติ**\n\n**เหตุผล:**...
8,[ ⬛️ Express] พัสดุ ⬛️⬛️ จัดส่งสำเร็จแล้ว ตรวจ...,**วิเคราะห์**: \nข้อความนี้มีลักษณะคล้ายการหล...,### ผลการวิเคราะห์ SMS: เป็น **ข้อความหลอกลวง ...
9,มีผู้เข้าสู่ระบบธนาคารของคุณจากอุปกรณ์อื่น หาก...,**ผลการวิเคราะห์ SMS:** ข้อความนี้เป็น **ข้อคว...,**วิเคราะห์ข้อความ SMS:** \n**ข้อความนี้เป็นข...

In [4]:
pd.set_option('display.max_colwidth', None)

df_results = pd.DataFrame(results)
display(df_results)

,Message,qwen3-32b,glm-4.5-air
0,"ธนาคารได้อนุมัติวงเงิน50,000บาทติดต่อรับสิทธิ์: https://rb.gy/2erksz","**วิเคราะห์ SMS:** \nข้อความเริ่มต้นด้วยข้อความเชิงล่อลวงว่า ""ธนาคารได้อนุมัติวงเงิน50,000บาท"" ซึ่งมักเป็นเทคนิคมาตรฐานของแสกมเมอร์ที่ใช้สร้างความน่าสนใจโดยไม่ต้องผู้รับอนุมัติล่วงหน้า \n- **ลิงก์ที่น่าสงสัย**: ลิงก์ที่สั้น (`https://rb.gy/2erksz`) และไม่เชื่อมโยงกับโดเมนธนาคารหลักในไทย (เช่น `scb.co.th`, `kbank.co.th`) จัดเป็นลิงก์ที่แสกมเมอร์ตั้งขึ้นเพื่อกำหนดเป้าหมาย \n- **การใช้ภาษาและไวยากรณ์ผิดรูปแบบ**: คำว่า ""ติดต่อรับสิทธิ์"" สะท้อนการออกแบบข้อความด้วยเครื่องมือแปลภาษาอัตโนมัติ ซึ่งไม่เป็นไปตามข้อความทางการของธนาคาร \n- **การสร้างอารมณ์สู่การคลิกทันที**: แสกมเมอร์ใช้คำกระตุ้นเช่น ""รีบติดต่อ"" (แม้จะไม่เขียนครบถ้วนในข้อความนี้) เพื่อหลอกให้เห็นผลเร็วโดยไม่ตรวจสอบรายละเอียด \n\n**เหตุผลจัดเป็นข้อความจากแสกมเมอร์** \n1. **ลิงก์ปลอม**: ลิงก์ที่เชื่อมโยงไปยังไซต์ที่ไม่ปลอดภัย อาจนำผู้ใช้งานไปยังหน้ารวบรวมข้อมูลหรือดาวน์โหลดมัลแวร์ \n2. **การหลอกให้คลิกโดยไม่ยืนยันตัวตน**: ไม่ปรากฏข้อมูลติดต่อหรือชื่อบริษัทที่ชัดเจน \n3. **ใช้ประโยชน์จากความไว้วางใจในธนาคาร**: แอบอ้างชื่อบริษัทเพื่อลดการตั้งคำถามจากผู้รับ \n\n**สรุปผล** \n✅ **ข้อยืนยัน**: ข้อความนี้เป็น SMS แสกมที่ปลอมตัวเป็นธนาคารและหลอกให้คลิกลิงก์เพื่อนำทางไปยังเป้าหมายอันตราย \n❌ ไม่ควรกดลิงก์ดังกล่าว ให้ตรวจสอบกับธนาคารผ่านช่องทางหลัก (เช่น เว็บไซต์หรือแอปพลิเคชันที่เป็นทางการ) หรือโทรไปสายด่วนของธนาคารโดยตรง","## การวิเคราะห์ SMS: ธนาคารได้อนุมัติวงเงิน50,000บาทติดต่อรับสิทธิ์\n\n### ผลการวิเคราะห์: **ข้อความจากแสกมเมอร์ (Scam Message)**\n\n### เหตุผลที่บ่งชี้ว่าเป็นแสกมเมอร์:\n\n1. **การอ้างถึงสิทธิพิเศษที่น่าสงสัย**: \n - การอนุมัติวงเงิน 50,000 บาทโดยไม่ผ่านกระบวนการพิจารณาจริงอย่างที่ธนาคารปกตีทำ\n - การเสนอสิทธิ์ที่ดีเกินไปจริงในไม่มีเงื่อนไขหรือหลักเกณฑ์การให้บริการ\n\n2. **ลิงก์แปลกปลอม**:\n - URL ""https://rb.gy/2erksz"" ไม่ใช่เว็บไซต์ทางการของธนาคารใดๆ\n - ลิงก์สั้นแบบนี้มักนำไปยังเว็บไซต์หลอกลวงที่จะขโมยข้อมูลส่วนตัวหรงินฝาก\n\n3. **การไม่ระบุชื่อธนาคารชัดเจน**:\n - ข้อความไม่ได้ระบุว่าเป็นธนาคารอะไรที่แน่นอน (เช่น ธนาคารกรุงไทย, ธนาคารกรุงเทพ, ธนาคารไทยพาณิชย์)\n\n4. **การกระตุ้นให้กระทำทันที**:\n - ใช้คำว่า ""ติดต่อรับสิทธิ์"" เพื่อสร้างความเร่งรีบและเข้าใจผิดว่าเป๋าหน้าที่จำกัดเวลา\n\n5. **รูปแบบข้อความไม่เป็นทางการ**:\n - ข้อความสั้นๆ ไม่มีข้อมูลติดต่อหรือข้อมูลเพิ่มเติมตามมาตรฐานของธนาคาร\n\n### ข้อควรระวัง:\n- **ไม่คลิกลิงก์ในข้อความ SMS ที่ไม่ได้รับรอง**\n- **ตรวจสอบกับธนาคารโดยตรงผ่านช่องทางที่ปลอดภัย** (เช่น แอพธนาคาร, โทรศัพท์จริง, สาขาธนาคาร)\n- **ไม่กรอกข้อมูลส่วนตัว/ข้อมูลการเงินผ่านลิงก์ที่ไม่น่าเชื่อถือ**\n\n### แนวทางป้องกัน:\n- ติดตั้งแอปธนาคารทางการของทุกธนาคารที่คุณใช้งาน\n- เปิดใช้งานการแจ้งเตือนธนาคารผ่าน SMS หรืออีเมลที่ได้ลงทะเบียนไว้\n- รายงานข้อความหลอกลวงผ่านช่องทางอย่างเป็นทางการ (เช่น โทร 1326 ของ คอมพิวเตอร์คราวฟันดิ้ง)\n\nข้อความนี้เป็นตัวอย่างคลาสสิกของแสกมเมอร์ที่เลียนแบบการส่งข้อความจากธนาคารเพื่อล่อลวงให้ผู้รับคลิกลิงก์ปลอมและขโมยข้อมูลการเงิน"
1,คุณได้รับคืนเงินประกันมิเตอร์ไฟฟ้าส่วนภูมิภาค PEA ซึ่งจะคืนตามขนาดของมิเตอร์ที่ใช้ สามารถสอบถามเพิ่มเติมได้ที่ https://bit.ly/44jHSpi,"**ผลการวิเคราะห์ SMS: ข้อความนี้เป็น **""ข้อความจากแสกมเมอร์"" (Scam)** \n**เหตุผล:**\n\n1. **ใช้ชื่อบริษัทที่น่าเชื่อถือเพื่อลวงความสนใจ:** \n - ใช้ชื่อ ""มิเตอร์ไฟฟ้าส่วนภูมิภาค PEA"" ซึ่งเป็นผู้ให้บริการไฟฟ้าในพื้นที่จริง และเป็นชื่อที่ผู้ใช้รู้จักดีในประเทศไทย\n\n2. **มีข้อเสนอเงินคืนโดยไม่ชัดเจน:** \n - ข้อความกล่าวถึง ""คุณได้รับคืนเงินประกัน"" โดยไม่ได้ระบุเหตุผลหรือข้อกำหนดชัดเจน ซึ่งเป็นวิธีการแสกมที่มักใช้เพื่อดึงความสนใจให้คลิกลิงก์.\n\n3. **ใช้ลิงก์อัญเชิญ (Bitly Short Link):**\n - การใช้ Link แบบ short link (เช่น ""https://bit.ly/44jHSpi"") เป็นการปกปิดปลายทางเชิงลึกของลิงก์ ซึ่งอาจนำไปสู่เว็บไซต์ปลอมเพื่อขโมยข้อมูลส่วนตัว เช่น ชื่อผู้ใช้ เลขบัญชีธนาคาร หรือรหัส OTP\n\n4. **ไม่ระบุชื่อหรือเบอร์ผู้ส่งอย่างแน่ชัด:** \n - ข้อความไม่ระบุชื่อผู้ส่งอย่างเป็นทางการจาก PEA ไม่มีเบอร์ติดต่ออย่างชัดเจน ซึ่งเป็นลักษณะแปลกสำหรับข้อมูลจากรัฐหรือบริษัทที่มีชื่อเสียง\n\n---\n\n**สรุป:**\nSMS นี้มีลักษณะการหลอกลวง (Scam) อย่างชัดเจน ไม่เคยมีนโยบายการคืนเงินประกันแบบนี้จากบริษัท PEA โดยไม่แจ้งล่วงหน้าหรือใช้ช่องทางทางการ\n\n### คำแนะนำ:\nหากคุณได้รับ SMS ดังกล่าว ควร:\n\n- ❌ **อย่าคลิกลิงก์เด็ดขาด**\n- 🆘 **แจ้งหน่วยงานความปลอดภัยทางไซเบอร์ไทย (ปชส.)** หรือแจ้ง 1621\n- 🔍 **ตรวจสอบข้อมูลผ่านทางเว็บไซต์ PEA อย่างเป็นทางการ** เฉพาะ\n\n### การตรวจสอบเพิ่มเติม:\nเว็บไซต์อย่างเป็นทางการของ **ส่วนภูมิภาค การไฟฟ้าภูมิภาค (PEA)**: [www.pea.co.th](https://www.pea.co.th) \nไม่มีนโยบายการแจ้งเงินคืนหรือเงินประกันแบบ SMS ก่อนไม่มีการแจ้งทางการล่วงหน้า\n\n--- \n\n**หากคุณต้องการ สามารถส่ง SMS อื่นเพิ่มเติมเพื่อให้วิเคราะห์ต่อได้**.","## การวิเคราะห์ข้อความ SMS\n\n**ผลการวิเคราะห์: ข้อความนี้เป็นข้อความหลอกลวง (Scam)**\n\n### เหตุผลที่ระบุว่าเป็นข้อความหลอกลวง:\n\n1. **การใช้ลิงก์ย่อที่น่าสงสัย**\n - ลิงก์ ""https://bit.ly/44jHSpi"" เป็น URL ที่ถูกย่อแล้ว ซึ่งเป็นลักษณะเฉพาะของข้อความหลอกลวง\n - หน่วยงานราชการอย่าง PEA ไม่ค่อยจะใช้ลิงก์ย่อในการสื่อสารอย่างเป็นทางการ\n\n2. **เนื้อหาที่ไม่เป็นไปตามขั้นตอนปกติ**\n - PEA ไม่ได้มีการคืนเงินประกันมิเตอร์ไฟฟ้าในลักษณะที่แจ้งผ่าน SMS\n - หากมีการคืนเงิน จะเป็นการโอนเข้าบัญชีธนาคารโดยตรง ไม่ใช่ผ่านลิงก์\n\n3. **ข้อความที่ไม่มีข้อมูลส่วนตัว**\n - ข้อความไม่ระบุชื่อผู้รับ หมายเลขสัญญา หรือข้อมูลใดๆ ที่สามารถตรวจสอบได้\n - ข้อความมีลักษณะทั่วไปและไม่เฉพาะเจาะจง\n\n4. **ขาดการระบุตัวตนของผู้ส่ง**\n - ข้อความไม่มีชื่อหน่วยงาน หรือหมายเลขที่สามารถตรวจสอบได้\n\n### ข้อควรระวัง:\n- อย่าคลิกที่ลิงก์ในข้อความที่ไม่รู้จัก\n- ห้ามกรอกข้อมูลส่วนตัวหรือข้อมูลธนาคารผ่านลิงก์ที่ได้รับ\n- หากต้องการตรวจสอบ ให้ติดต่อ PEA โดยตรงผ่านช่องทางที่เชื่อถือได้\n\n**นี่คือข้อความหลอกลวงที่มุ่งเป้าที่ขโมยข้อมูลส่วนตัวของผู้รับหรือนำไปสู่ภัยคุกคามทางไซเบอร์**"
2,"KMA ยื่นสิทธิ์การกู้ให้ท่าน 120,000 บาท คลิก: citly.me/eq9br","ข้อความ **""KMA ยื่นสิทธิ์การกู้ให้ท่าน 120,000 บาท คลิก: citly.me/eq9br""** ย่อมถือเป็น **ข้อความหลอกลวง (Scam SMS)** โดยมีเหตุผลรองรับดังนี้:\n\n---\n\n### **1. การใช้ชื่อหน่วยงานรัฐเพื่อสร้างความน่าเชื่อถือ (Spoofing)**\n- **KMA (กรมธรรม์บำเหน็จบำหรุญแผ่นดิน)** เป็นหน่วยงานของรัฐที่สหวิทยาการมักถูกระบุชื่อเพื่อเลียนแบบข้อมูลการให้สิทธิ์ทางการเงินหรือการกู้ยืม\n- ข้อความจริงใจจากหน่วยงานรัฐไทยจะใช้ชื่ออย่างเป็นทางการ (เช่น กรมสรรพากร, ธนาคารแห่งชาติ) และไม่ใช้คำสั้นๆแบบ ""KMA"" ซ้ำๆ\n- การส่งข้อความแบบไม่ระบุชื่อผู้ส่ง และเสนอเงินกู้โดยไม่สอดคล้องกับบริบทหน้าที่ของ KMA ชัดเจนว่าเป็นการตัดต่อยอดเพื่อหลอกลวง\n\n---\n\n### **2. ลักษณะของลิงก์ (Phishing Link)**\n- **ลิงก์สั้น ""citly.me/eq9br""** เป็นลิงก์ที่ถูก shortening ซึ่งปกติแสกมเมอร์ใช้เพื่อซ่อน URL เต็มรูปแบบ ทำให้น่ากลัวและเป็นจุดตรวจจับหลักว่าเป็นแสกม\n- การตรวจสอบผ่านเครื่องมือตรวจสอบ URL เช่น [Google Phishing Report](https://transparencyreport.google.com/phishing/) หรือ [VirusTotal](https://www.virustotal.com) จะพบว่าลิงก์ดังกล่าว **ไม่เชื่อมโยงกับเว็บไซต์รัฐบาลหรือสถาบันการเงินที่ได้รับการรับรอง** และอาจเป็นไปยังเว็บปลอมเพื่อขอข้อมูลส่วนบุคคล\n\n---\n\n### **3. ข้อเสนอเงินกู้แบบไม่ได้คาดฝัน (Unsolicited Loan Offer)**\n- การเสนอเงินกู้หรือผลประโยชน์ทางการเงินโดยไม่ได้รับการขอให้บริการ **เป็นเทคนิคหลอกลวงมาตรฐาน** ของแสกมเมอร์ เพราะผู้ถูกหลอกอาจถูกดึงให้สมัครโดยไม่ตั้งใจ\n- **KMA ไม่ดำเนินการกู้ยืมเงิน** แต่ดูจากการแอบอ้างบทบาท แสกมมีจุดประสงค์แฝง เช่น ให้ผู้ใช้เปิดลิงก์เพื่อกรอกข้อมูลส่วนบุคคลหรือดาวน์โหลดมัลแวร์\n\n---\n\n### **4. การไม่ระบุข้อมูลส่วนตัว (Lack of Personalization)**\n- ข้อความนี้ไม่ได้ระบุข้อมูลส่วนตัว (ชื่อ-นามสกุล, เลขที่บัญชีภาษีอากร) ซึ่งเป็นข้อมูลที่หน่วยงานรัฐ **มักต้องแนบมาในข้อความทางการ**\n- การที่ไม่มีข้อมูลเฉพาะตัวบ่งชี้ว่าข้อความอาจถูกส่งแบบกระจายให้กับผู้ติดต่อทั้งหมด (Mass Mailing) ซึ่งคือสัญญาณว่าเป็นแสกม\n\n---\n\n### **5. การสร้างความเร่งหน่วง (Urgency)**\n- คำว่า **""ยื่นสิทธิ์""** (รีบดำเนินการเพื่อรับสิทธิ์) เป็นเทคนิคที่แสกมเมอร์ใช้เพื่อ **กดดันให้ผู้ใช้คลิกลิงก์โดยไม่ไตร่ตรอง**\n- การหลอกลวงด้วยความเร่งด่วนมักเป็นเพื่อทำลายความระมัดระวังของผู้ใช้ เพื่อให้หลงเชื่อข้อมูลลวง\n\n---\n\n### **6. ข้อความสั้นไม่เป็นทางการ (Grammatical Irregularities)**\n- แม้ข้อความจะใช้ภาษากลางของไทยโดยทั่วไป แต่การตั้งประโยคแบบไม่สมบูรณ์และไม่ถูกต้องตามหลักการสื่อสารเป็นทางการ (เช่น การใช้คำว่า ""ยื่นสิทธิ์"" ไม่ได้ถูกเน้นว่าเป็นเงื่อนไขหรือขั้นตอนอะไร) มักเกิดจากนักแสกมที่ไม่มีความรู้เรื่องการสื่อสารแบบรูปธรรม\n\n---\n\n### **สรุปผล**\n**ข้อความนี้เป็น Scam SMS** และมีลักษณะที่ตรงกับข้อสงสัยหลายประการตามข้างต้น ผู้รับควรระมัดระวังและ **ไม่คลิกลิงก์ใน SMS ไม่มีความโปร่งใส** ส่วนขั้นตอนการป้องกัน:\n- อย่าเปิดลิงก์หรือโทรกลับ\n- ตรวจสอบผ่านเว็บไซต์หรือแอปหลักของหน่วยงาน (เช่น [www.rd.go.th](https://www.rd.go.th) สำหรับกรมสรรพากร)\n- แจ้งเบาะแสไปยัง [ศูนย์ความช่วยเหลือด้านไซเบอร์ (HDA)](https://www.hda.or.th) หรือตำรวจไซเบอร์\n\n> *หมายเหตุ*: แสกมเมอร์มักใช้ชื่อหน่วยงานรัฐเพื่อสร้างความไว้วางใจ แต่ลิงก์หรือเบอร์ติดต่อมักเป็นของกลางจริงหรือไซต์ปลอม ควรยืนยันผ่านช่องทางหลักก่อนปฏิบัติตามเสมอ.","### การวิเคราะห์ข้อความ SMS\n\n**ข้อสรุป:** ข้อความนี้เป็น **ข้อความหลอกลวง (Phishing SMS)** จากแสกมเมอร์ ควรทราบและหลีกเลี่ยงทันที\n\n---\n\n### รายละเอียดการวิเคราะห์:\n\nคุณได้รับข้อความที่อ้างว่ามาจาก ""KMA"" (ซึ่งอาจหมายถึง การไฟฟ้าส่วนภูมิภาค - MEA โดยที่ผู้โจมตีใช้ตัวย่อผิดพลาดเป็น KMA) โดยเสนอเงินทุนสนับสนุนจำนวน 120,000 บาท พร้อมลิงก์ที่ให้คลิก\n\n**เหตุผลที่ทำให่่เชื่อว่าเป็นข้อความหลอกลวง:**\n\n1. **ความน่าสงสัยของเนื้อหาและข้อเสนอ:**\n * **ไม่มีพื้นฐาน:** การได้รับเงินทุนสนับสนุนจำนวนมากโดยไม่ต้องผ่านการสมัครรับเลือกหรือตรวจสอบใดๆ เป็นเรื่องที่เป็นไปไม่ได้ในโลกแห่งความเป็นจริง หน่วยงานราชการหรือรัฐวิสาหกิจมักมีขั้นตอนที่ชัดเจนและซับซ้อน\n * **การใช้ลิงก์สั้นที่น่าสงสัย:** `citly.me/eq9br` เป็นลิงก์สั้นที่สร้างโดยบริการย่อ URL ซึ่งเป็นเครื่องมือที่ผู้โจมตีใช้อยู่บ่อยครั้ง เพื่อซ่อน URL จริงที่อาจเป็นเว็บไซต์อันตรายหรือเพจล็อกอินปลอมไว้\n\n2. **ลักษณะทั่วไปของการโจมตีแบบ Phishing:**\n * **สร้างความรีบร้อน (Urgency):** ข้อความนี้ใช้เทคนิคการสร้างความรู้สึกที่คุณต้องด่วนทำอะไรสักอย่าง ก่อนที่ข้อเสนอดีๆ จะหายไป\n * **กระตุ้นให้คลิกลิงก์:** เป้าหมายหลักคือการให้ผู้รับกดลิงก์เพื่อเข้าสู่เว็บไซต์ปลอม เมื่อคลิกแล้ว คุณอาจถูกนำไปสู่:\n * **หน้าล็อกอินปลอม** ของธนาคาร กรมธรรม์ หรือบัญชีออนไลน์อื่นๆ เพื่ขโมยข้อมูลเข้าสู่ระบบ\n * **หน้าดาวน์โหลดไฟล์** ที่มีมัลแวร์หรือไวรัส\n * **หน้าฟิชชิ่ง** ที่ขอข้อมูลส่วนตัว เช่น หมายเลขบัตรประชาชน หมายเลขโทรศัพท์ เบอร์บัตรเครดิต และรหัส PIN\n\n3. **ข้อผิดพลาดในข้อความ:**\n * ในข้อความมีคำว่า ""**กู้**"" ซึ่งเป็นการพิมพ์ผิดที่ชัดเจนของคำว่า ""**กู้**"" แม้ว่าบางครั้งอาจเป็นการพิมพ์ผิดโดยไม่ได้ตั้งใจ แต่ในกรณีของข้อความหลอกลวง มักจะมีข้อผิดพลาดเล็กน้อยแบบนี้เพื่อหลีกเลี่ยงการตรวจจับจากระบบค้นหาทั่วไป\n\n---\n\n### แนวทางป้องกันและการปฏิบัติต่อไป:\n\n1. **อย่าคลิกลิงก์ให้เด็ดขาด:** ไม่ว่าจะเป็นลิงก์ใน SMS, อีเมล หรือข้อความจากบุคคลที่ไม่รู้จัก ให้หลีกเลี่ยงการคลิกโดยตรง\n2. **ลืมข้อความนี้ไป:** ไม่ต้องกลัวว่าจะพลาดโอกาส หากเป็นข้อเสนอจากหน่วยงานจริง คุณจะสามารถติดตามข่าวสารได้จากช่องทางที่เชื่อถือได้เสมอ\n3. **ลบข้อความทันที:** ลบข้อความนี้ออกจากอุปกรณ์ของคุณเพื่อป้องกันไม่ให้ผู้อื่นหลงเชื่อ\n4. **รายงานข้อความหลอกลวง:** คุณสามารถรายงานข้อความนี้ได้ผ่านแอพพลิเคชั่น Truecaller หรือรายงานต่อ True Corporation ได้โดยตรง\n5. **แชร์ข้อมูล:** แจ้งให้เพื่อนและคนในครอบครัวที่อาจได้รับข้อความแบบเดียวกันทราบ เพื่อเป็นการป้องกันกันร่วมกัน\n\n**สรุปอีกครั้ง: ข้อความนี้เป็นกลโกงที่ออกแบบมาเพื่อขโมยข้อมูลส่วนตัวและเงินของคุณ อย่าตอบรับหรือคลิกที่ใดๆ ในข้อความนี้**"
3,เงินเข้าโทรศัพท์ฟรี 500บาท กด*158# ลุ้นก่อนใคร สมัครดวงดีดวงเฮง 3บ/ขค,"**ผลการวิเคราะห์ SMS: ข้อความนี้เป็น **""ข้อความจากแสกมเมอร์""**\n\n---\n\n### **เหตุผลที่ระบุว่าเป็น SMS หลอกลวง (Scam Message):**\n\n1. **ข้อความเสนอเงินฟรี (Free Money):**\n - ข้อความเกี่ยวกับการได้รับเงิน 500 บาท ""ฟรี"" เป็นจุดดึงดูดที่แสกมเมอร์ใช้บ่อยๆ เพราะมนุษย์มีแนวโน้มตอบสนองด้วยความโลภหรือความอยา\n - ในความเป็นจริง ไม่มีเงินฟรีจากแหล่งใดแน่นอน โดยเฉพาะไม่ใช่จากค่ายใดในไทยหรือหน่วยงานภาครัฐ\n\n2. **การใช้รูปแบบ ""กด *158#"":**\n - การเสนอให้กดเลขทางโทรศัพท์ (กด *XXX#) เพื่อสมัครรับสิทธิ์ หรือเข้าร่วมกิจกรรมนั้นมีความเสี่ยงสูงถึง 2 ประการ:\n - **ค่าบริการเพิ่มเติม (ค่า 3B)**: ข้อความระบุ ""3บ/ขค"" (3 บาท/ครั้ง) ซึ่งเป็นค่าบริการเพิ่มเติมจากการกดเข้าสู่ระบบ มีแนวโน้มเกี่ยวข้องกับระบบบริการมูลค่าเพิ่ม (VMS) ที่ไม่ได้ให้อะไรตอบแทนจริง\n - **อาจถูกติดตั้งมัลแวร์**: หากกดเข้าไปผ่านแอปหรือเว็บไซต์ที่เชื่อมโยงกัน อาจถูกติดมัลแวร์\n\n3. **ศัพท์และภาษาที่ใช้เป็นภาษาบันเทิง/คาสิโน:**\n - ""ลุ้นก่อนใคร"", ""ดวงดีดวงเฮง"" เป็นต้น แสดงถึงแนวทางดึงดูดใจผู้คนผ่านอารมณ์และความคิดแบบ “ดวง” หรือ “เสี่ยงโชค”\n\n4. **ไม่มีชื่อบริการ ผู้ให้บริการ หรือผู้สนับสนุนชัดเจน:**\n - SMS ที่ถูกต้องจากบริษัทมีจริงจะระบุชื่อบริษัท/ผู้ให้สิทธิ์ หรือแหล่งที่มาอย่างชัดเจน แต่ข้อความนี้ไม่มีรายละเอียดดังกล่าว\n\n5. **ไม่มีช่องทางยืนยันหรือติดต่อกลับได้:**\n - ไม่มีเว็บไซต์ โทรศัพท์ หรือช่องทางใดที่สามารถติดต่อกลับเพื่อยืนยันว่าเป็นข้อความจริง\n\n---\n\n### **คำแนะนำเพื่อความปลอดภัย:**\n\n- **ห้ามกด *158#** หรือหมายเลขใดๆ ที่ไม่ได้รับการยืนยัน\n- **แจ้งเบาะแส** ไปยัง **ศูนย์ปราบปรามการกระทำความผิดด้านเทคโนโลยีสารสนเทศ (ปอท.)**\n - โทร: 1217\n - เว็บไซต์: [www.isc.go.th](http://www.isc.go.th)\n- **แจ้งให้ผู้คนรอบตัวตระหนักถึง SMS หลอกลวง** เพื่อป้องกันผู้คนอื่นๆ ไม่เสี่ยง\n\n---\n\n### **สรุป:**\n\n- **ประเภท SMS**: ข้อความหลอกลวง (Scam Message)\n- **คำเตือน**: อย่ากดใดๆ เป็นอันขาด\n- **ความเสี่ยง**: การเสียเงินจริงผ่านค่าบริการเพิ่มเติม (3 บาท/ครั้ง) และอาจถูกนำทางไปสู่เว็บไซต์ปลอดภัยน้อย\n\nหากท่านได้รับข้อความนี้ ขอแนะนำให้ลบและรายงานกับ ปอท. เลยครับ.","### วิเคราะห์ SMS: **""เงินเข้าโทรศัพท์ฟรี 500บาท กด*158# ลุ้นก่อนใคร สมัครดวงดีดวงเฮง 3บ/ขค""**\n\n#### ผลการวิเคราะห์: \n**🚨 SMS นี้เป็นข้อความหลอกลวงจากแสกมเมอร์ (Scammer) อันตราย แนะนำให้ละไว้เลย!**\n\n---\n\n### 📌 เหตุผลที่เป็นแสกมเมอร์:\n\n1. **เรื่อง ""เงินเข้าโทรศัพท์ฟรี"" และกด *158#** \n - แอบเพิ่มความน่าสนใจด้วยประโยค ""ฟรี"" และ ""ลุ้นก่อนใคร"" เพื่กระตุ้นให้ผู้รับเผื่อบางคนกด *158# \n - โค้ด `*158#` นี้เป็น **โค้ดภายในระบบที่ผู้โทรศัพท์ใช้เอง** ไม่ใช่ฟังก์ชันของผู้ให้บริการโทรศัพท์จริง \n - **อันตราย:** กดโค้ดนี้อาจทำให้หมายเลขโทรศัพท์ถูกโจมตี **สูญหายเงิน**, ถูกตั้งค่า **โอนเงินโดยอัตโนมัติ**, หรือเปิดช่องทางให้ **Malware** บนโทรศัพท์ \n\n2. **คำติดท้าย ""สมัครดวงดีดวงเฮง 3บ/ขค""** \n - คำว่า ""ดวงดี"", ""ดวงเฮง"" เป็น **คำวิบากที่แสกมเมอร์ใช้บ่อย** เพื่สร้างความน่าเชื่อถือ \n - ""3บ/ขค"" หมายถึง **""3บาทต่อข้อความ""** แสดงว่าผู้โทรศัพท์หากกด *158# จะถูก **โอนเงินไปยังบัญชีโกงต่อข้อความ** \n\n3. **ลักษณะทั่วไปของแสกมเมอร์** \n - ใช้ภาษาแบบ **""SMS Blast""** (ส่งให้หลายคนพร้อมกัน) ไม่มีชื่อผู้ส่ง \n - เนื้อหา ** ""ลุ้นก่อนใคร"" ** เป็นการสร้างการแข่งขันปลอยๆ เพื่ให้กระทำโดยไม่ระวัง \n - ไม่มี **ลิงก์หรือแอพระบบรองรับจากผู้ให้บริการโทรศัพท์จริง** (TrueMove, AIS, DTAC)\n\n---\n\n### ⚠️ วิธีป้องกัน:\n1. **ไม่กด *158# หรือโค้ดประหนึ่งใดใน SMS** \n - ถ้ามีข้อความฟรี/ลุ้น ให้ตรวจสอบกับ **Call Center โทรศัพท์จริง** หรือเว็บไซต์อย่างเป็นทางการ \n2. **ลบ SMS และบล็อกหมายเลขนี้** \n3. **แจ้งเบาะแสกับ คสช. (สายด่วน 1325)** และ **สำนักงานต้านอาชญากรรมทางไซเบอร์** \n\n### 💡 คำแนะนำ: \nถ้าคุณได้ SMS แบบนี้ สิ่งที่ควรทำคือ **""ละไว้เลย!""** และ **แชทกับเพื่อน/คนในครัวเรือนว่าเป็นแสกมเมอร์** เพื่อไม่ให้ใครถูกโกงต่อไป \n\n---\n\n### สรุป: \nSMS นี้เป็น **แนวโจรกรรมแบบ Classic SMS Scam** ที่ใช้ความต้องการ ""เงินฟรี"" เพื่ลวงให้กดโค้ดอันตราย ระวังเข้าไปเกือบเป็น **แนวทางเสียเงินจากโทรศัพท์** แถมยังส่งผลร้ายแรงต่อข้อมูลส่วนตัวอีกด้วย!"
4,รับฟรี 129 บาท ฝากแรกรับ 1599 บาท,"**การวิเคราะห์ข้อความ SMS:** \nข้อความนี้มีลักษณะคล้ายกับสแปมหรือการหลอกลวงผ่านระบบ **Social Engineering** อย่างชัดเจน ดังนี้:\n\n1. **ข้อเสนอเงินฟรีทันที (Too Good to Be True):** \n ข้อความเสนอ ""รับฟรี 129 บาท ฝากแรกรับ 1599 บาท"" ใช้คำว่า ""ฟรี"" และ ""รับเพิ่มทันที"" ซึ่งเป็นแนวทางหลอกให้เหยื่อยอมรับข้อเสนอโดยเร็ว ตามกลวิธี **Bait-and-Switch** (ตั้งกับดักแล้วเปลี่ยนเงื่อนไข) ที่แสกมเมอร์ใช้บ่อยในประเทศไทย\n\n2. **ไม่มีรายละเอียดชัดเจน:** \n ไม่ระบุชื่อผู้ให้บริการ ไม่มีเว็บไซต์หรือช่องทางติดต่ออย่างเป็นทางการ สะท้อนถึงการใช้ช่องทาง SMS แบบ Mass Messaging ซึ่งเป็นแนวทางของกลุ่มแสกม\n\n3. **ลักษณะการหลอกเรียกเงินแรกเข้า (First Deposit Trap):** \n การเสนอ ""ฝากแรกรับ 1599 บาท"" เป็นการหลอกให้เหยื่อยื่นมือให้ข้อมูลส่วนตัวหรือโอนเงินก่อน ตามรูปแบบ **Phishing** หรือการหลอกลวงผ่านระบบบัญชีเงินฝากที่ถูกออกแบบมาให้ไม่สามารถถอนเงินที่ตกลงไว้ได้จริง\n\n4. **สถิติในชุมชนไทย:** \n ขั้นตอนนี้ตรงกับรูปแบบการหลอกลวงผ่านการเสนอเงินคืน (คืนเงิน 100% หรือมากกว่า) ที่แสกมเมอร์ในไทยมักใช้ โดยหลอกให้ผู้เสียหายเปิดบัญชีหรือให้ข้อมูลธนาคารก่อน แล้วค่อยเรียกเก็บ ""ค่าธรรมเนียม"" หรือ ""ค่าความล่าช้า""\n\n---\n\n**ผลสรุป:** \n❌ **ข้อความนี้เป็นสแปมหรือการหลอกลวงจากแสกมเมอร์** \n**เหตุผล:** ใช้เทคนิคการหลอกด้วยเงินฟรี ไม่มีแหล่งที่มาชัดเจน และสอดคล้องกับรูปแบบการลวงทั่วไปในประเทศไทย\n\n**คำแนะนำ:** \n- อย่าคลิกลิ้งค์หรือให้ข้อมูลส่วนตัว \n- ตรวจสอบชื่อบริษัทผ่านกรมการค้าภายใน หากไม่มีข้อมูลชัดเจน ให้ถือว่าเป็นมิจฉาชีพ \n- แจ้งความร้องเทียนได้ที่ **ศูนย์แจ้งความออนไลน์ (www.thaicyberpolice.org)**","### การวิเคราะห์ข้อความ SMS: **""รับฟรี 129 บาท ฝากแรกรับ 1599 บาท""**\n\n#### **ผลลัพธ์: ข้อความหลอกลวงจากแสกมเมอร์** \n**เหตุผลที่สำคัญ:**\n\n1. **เนื้อหาดึงดูดผิดธรรมชาติ** \n - เสนอ ""เงินฟรี"" และโบนัสสูงโดยไม่ระบุแหล่งที่มา (ชื่อบริษัท โปรโมชั่นอย่างเป็นทางการ) \n - จำนวนเงิน (129 บาท + 1599 บาท) ที่ไม่สอดคล้องกับโปรโมชั่นจริงของธนาคาร/บริษัท\n\n2. **สแตนดาร์ดแสกมเมอร์** \n - ใช้รูปแบบคลาสสิกของ SMS หลอกลวง: **""ข้อความสั้น + เงินที่น่าสนใจ + การกระตุ้นให้ติดต่อกลับ""** \n - ไม่มีลิงก์เว็บไซต์หรือรายละเอียดเพื่อยืนยันความถูกต้อง\n\n3. **ละเมิดกฎหมายไทย** \n - ตาม **พ.ร.บ. การป้องกันและปราบปรามการฉ้อโกงออนไลน์ พ.ศ. 2560** \n - ต้องแจ้งชื่อเจ้าของบริการ ระบุรายละเอียดโปรโมชั่นชัดเจน \n - **ข้อความนี้ไม่มีข้อมูลดังกล่าว → มีความเสี่ยงสูง**\n\n4. **เป้าหมายของแสกมเมอร์** \n - **สร้างความสงสัย**: ผู้รับอาจติดต่อกลับเพื่อสอบถาม ทำให้เปิดช่องให้แสกมเมอร์ขอข้อมูลส่วนตัว (เบอร์โทรศัพท์ บัญชีธนาคาร) \n - **นำไปสู่การหลอกเงิน**: อาจขอ OTP หรือข้อมูลการฝากเงินเพื่อ ""เปิดโบนัส"" แต่จนท้ายที่สุดจะหายไป\n\n#### **ข้อแนะนำสำหรับผู้รับ** \n- **ไม่ตอบกลับหรือลบข้อความทันที** \n- **รายงานผ่านช่องทางที่เชื่อถือได้**: \n - ระบบ **1650** (ฝ่ายปราบปรามการฉ้อโกงออนไลน์) \n - แอป **ไทยรักษาความปลอดภัย** (สำนักงานคณะกรรมการข่าวกลาง) \n- **ตรวจสอบกับธนาค้า/บริษัทโดยตรง** หากมีความสงสัยโปรโมชั่น \n\n> ⚠️ **หมายเหตุ**: ในประเทศไทย มีกรณีแสกมเมอร์ใช้ชื่อ ""ธนาคารกรุงไทย"" หรือ ""กสิกรไทย"" ปลอมเพื่อหลอกเงินผู้ใช้ ข้อความนี้ตรงตามรูปแบบนั้น 100%"